server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: "jdbc:mysql://localhost:3306/jasper_report"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
springdoc:
  api-docs:
    path: /api-docs
